### ISSUE TITLE
ImportError: No module named 'apiai'

### ISSUE THREAD

**Issue by vprzero** [api-ai/apiai-python-client#26]
I am getting the following error while trying to run the example for text input

Traceback (most recent call last):
  File "/home/vpr/mysite/flask_app.py", line 2, in <module>
    import apiai
ImportError: No module named 'apiai'
>>> 

I think there is a mistake in the module, could it be checked?

**Comment by sstepashka** [comment]
Did you use pip? Have you installed apiai by the pip?

**Comment by iPoul** [comment]
Make sure you use the right pip to install the package as the version of python you use to run your script.

Your pip might have installed for python 2.7 and your running the script under python3 etc ...

**Comment by maxsteel11hour** [comment]
I encountered the error when I installed the apiai package based on pip3.5 but the script ran in py3.6
Thus, did pip3.6
