### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ApiAI'

### ISSUE THREAD

**Issue by ocihangir** [api-ai/apiai-python-client#29]
I have installed apiai by : 
$ apt-get install python-pyaudio python-numpy
$ pip install apiai

When I run "send_text_example.py", I get the following error : 

ai = apiai.ApiAI(CLIENT_ACCESS_TOKEN)
AttributeError: 'module' object has no attribute 'ApiAI'

If I clone the repo to my local, I can run it successfully.

**Comment by sstepashka** [comment]
Do you have some file named "apiai.py" in your project? Do you know how to working import in python?

**Comment by ocihangir** [comment]
Yeap this was the problem. My bad.
